# Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        paths:
          - "!**/*_test.go"
          - "!**/testdata/**"
          - "!**/mock/**"
    
    patch:
      default:
        target: 80%
        threshold: 2%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/testdata"
  - "**/mock"
  - "cmd/**"
  - "examples/**"
  - "docs/**"
  - "scripts/**"