# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata
    - examples

linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gocyclo
    - dupl
    - misspell
    - lll
    - nakedret
    - prealloc
    - exportloopref
    - gocritic
    - goimports
    - revive
    - unconvert
    - unparam
    - errorlint
    - goconst
    - godot
    - godox
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  
  govet:
    check-shadowing: true
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  lll:
    line-length: 120
    tab-width: 4
  
  misspell:
    locale: US
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  godox:
    keywords:
      - TODO
      - FIXME
      - HACK
  
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    
    # Exclude known issues in generated files
    - path: generated
      linters:
        - golint
        - stylecheck
    
    # Exclude lll in long lines with URLs
    - linters:
        - lll
      source: "https://"
  
  max-issues-per-linter: 50
  max-same-issues: 3