name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build binaries
      run: |
        # Extract version information
        VERSION=$(cat VERSION)
        GIT_COMMIT=$(git rev-parse --short HEAD)
        BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        GO_VERSION=$(go version | awk '{print $3}')
        
        # Build flags
        LDFLAGS="-X 'github.com/suparena/entitystore.Version=$VERSION'"
        LDFLAGS="$LDFLAGS -X 'github.com/suparena/entitystore.GitCommit=$GIT_COMMIT'"
        LDFLAGS="$LDFLAGS -X 'github.com/suparena/entitystore.BuildDate=$BUILD_DATE'"
        LDFLAGS="$LDFLAGS -X 'github.com/suparena/entitystore.GoVersion=$GO_VERSION'"
        
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/indexmap-pps-linux-amd64 ./cmd/indexmap
        GOOS=linux GOARCH=arm64 go build -ldflags "$LDFLAGS" -o dist/indexmap-pps-linux-arm64 ./cmd/indexmap
        GOOS=darwin GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/indexmap-pps-darwin-amd64 ./cmd/indexmap
        GOOS=darwin GOARCH=arm64 go build -ldflags "$LDFLAGS" -o dist/indexmap-pps-darwin-arm64 ./cmd/indexmap
        GOOS=windows GOARCH=amd64 go build -ldflags "$LDFLAGS" -o dist/indexmap-pps-windows-amd64.exe ./cmd/indexmap
    
    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          dist/*
        generate_release_notes: true